include:
  - board: xiao_ble/nrf52840/zmk
    shield: lalapadmini_right rgbled_adapter
    snippet: studio-rpc-usb-uart
  - board: xiao_ble/nrf52840/zmk
    shield: lalapadmini_left rgbled_adapter
  - board: xiao_ble/nrf52840/zmk
    shield: settings_reset